# Generated by Django 5.0.7 on 2024-08-03 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField(verbose_name='Ação')),
                ('timestamp', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Comentários')),
                ('creation_date', models.DateField(verbose_name='Criação')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nome de usuário')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Titúlo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('due_date', models.DateField(verbose_name='Prazo')),
                ('creation_date', models.DateField(verbose_name='Criação')),
                ('completion_date', models.DateField(verbose_name='Finalização')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.category')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.user')),
            ],
        ),
    ]
